'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],asset=p=>window.SITE_ASSETS?.[p]||p,content=window.SITE_CONTENT,reduce=matchMedia('(prefers-reduced-motion: reduce)');
let paused=reduce.matches,filter='all',limit=6,currentProject=0,projectSet=[];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.documentElement.classList.add('js-motion');const reveals=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveals.unobserve(e.target);}}),{threshold:.06});$$('.reveal').forEach(e=>reveals.observe(e));
const menu=$('.menu-toggle'),nav=$('#navigation');
function closeDropdowns(except){$$('.nav-group').forEach(g=>{if(g!==except){g.classList.remove('expanded');$('.nav-category',g).setAttribute('aria-expanded','false');}});}
function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');closeDropdowns();}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';nav.classList.toggle('open',open);menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');});
$$('.nav-group').forEach(g=>{const b=$('.nav-category',g);function open(){closeDropdowns(g);g.classList.add('expanded');b.setAttribute('aria-expanded','true');}b.addEventListener('click',()=>{if(g.classList.contains('expanded')){g.classList.remove('expanded');b.setAttribute('aria-expanded','false');}else open();});g.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'&&innerWidth>900)open();});g.addEventListener('pointerleave',()=>{if(innerWidth>900&&!g.contains(document.activeElement))closeDropdowns();});g.addEventListener('focusout',()=>setTimeout(()=>{if(!g.contains(document.activeElement)){g.classList.remove('expanded');b.setAttribute('aria-expanded','false');}},0));});
$$('a',nav).forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('click',e=>{if(!e.target.closest('.header'))closeMenu();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
$$('.service').forEach(d=>d.addEventListener('toggle',()=>{if(d.open)$$('.service').forEach(o=>{if(o!==d)o.open=false;});}));
function toolIcon(slug){return `<img src="${asset('assets/tools/'+slug+'.svg')}" alt="" width="26" height="26"><span>${esc(content.toolNames[slug])}</span>`;}
function renderTools(group){$('#tools-grid').innerHTML=content.toolGroups[group].map(t=>`<a class="tool-card" href="https://www.google.com/search?q=${encodeURIComponent(content.toolNames[t]+' software')}" target="_blank" rel="noopener" aria-label="Learn about ${esc(content.toolNames[t])} on Google">${toolIcon(t)}<span class="tool-link-arrow" aria-hidden="true">↗</span></a>`).join('');$$('[data-tools]').forEach(b=>{const active=b.dataset.tools===group;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});}
$$('[data-tools]').forEach(b=>b.addEventListener('click',()=>renderTools(b.dataset.tools)));renderTools('design');
const sd=$('#service-dialog');let chosenService='';
function openService(id){const s=content.services[id];if(!s)return;chosenService=id;$('#service-category').textContent=s.category==='marketing'?'DIGITAL MARKETING':s.category.toUpperCase();$('#service-title').textContent=s.title;$('#service-description').textContent=s.description;$('#service-deliverables').replaceChildren(...s.deliverables.map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));$('#service-tools').innerHTML=s.tools.map(t=>`<span>${toolIcon(t)}</span>`).join('');sd.showModal();}
$$('[data-service-id]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();closeMenu();openService(a.dataset.serviceId);}));
$('#service-cta').addEventListener('click',()=>{const s=content.services[chosenService];$('#service-choice').value=s.category==='marketing'?'Digital marketing':chosenService==='data-analytics'?'Data analytics':chosenService==='automation'?'AI and automation':s.category==='development'?'Web development':['animation','video-production','3d-design'].includes(chosenService)?'Motion and video':chosenService==='ui-ux'?'UI/UX design':'Branding and design';sd.close();});
if(location.hash.startsWith('#service-'))openService(location.hash.slice(9));
function renderProjects(){projectSet=content.projects.filter(p=>filter==='all'||p.category===filter);const shown=projectSet.slice(0,limit);$('#portfolio-grid').innerHTML=shown.map(p=>`<${p.id==='hotel'?'a':'button'} class="project real-project" ${p.id==='hotel'?'href="'+p.url+'" target="_blank" rel="noopener"':'data-project-id="'+p.id+'"'}><div class="project-visual project-${p.category}">${p.category==='web'?'<div class="project-browser-bar"><span>● ● ●</span><span>itfume.com</span></div>':''}<img src="${asset(p.image)}" alt="${esc(p.title+' / '+p.label)}" loading="lazy">${p.vimeo?'<span class="project-play">▷</span>':''}<span class="project-type">${p.category==='uiux'?'UI/UX DESIGN':p.category==='web'?'CLIENT WEBSITE':p.category==='data'?'TABLEAU STORY':p.category==='motion'?'MOTION & VIDEO':'CAMPAIGN DESIGN'}</span><span class="project-open">↗</span></div><div class="project-meta"><h3>${esc(p.title)}<span>↗</span></h3><p>${esc(p.label)}</p></div></${p.id==='hotel'?'a':'button'}>`).join('');$('#project-count').textContent=`${shown.length} of ${projectSet.length} projects`;$('#more-projects').hidden=shown.length>=projectSet.length;$$('[data-project-id]').forEach(b=>b.addEventListener('click',()=>{currentProject=projectSet.findIndex(p=>p.id===b.dataset.projectId);showProject();$('#project-dialog').showModal();}));}
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;limit=6;$$('[data-filter]').forEach(x=>{const active=x===b;x.classList.toggle('active',active);x.setAttribute('aria-pressed',String(active));});renderProjects();}));$('#more-projects').addEventListener('click',()=>{limit+=6;renderProjects();});renderProjects();
function showProject(){const p=projectSet[currentProject];let media=`<img class="dialog-project-image" src="${asset(p.image)}" alt="${esc(p.title)}">`,extras='';if(p.vimeo){media=`<div class="vimeo-player"><iframe src="https://player.vimeo.com/video/${p.vimeo}?title=0&byline=0&portrait=0&dnt=1" title="${esc(p.title)}" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe></div>`;extras=`<p class="media-note">Video playback requires an internet connection. <a href="https://vimeo.com/${p.vimeo}" target="_blank" rel="noopener">Open on Vimeo ↗</a></p>`;}if(p.id==='itfume')extras='<div class="case-detail"><h3>A clear home for a technical offer.</h3><p>Hosting services, domain search and customer support, organised around the decisions a visitor needs to make.</p><a class="button button-blue" href="https://itfume.com/" target="_blank" rel="noopener">Visit the client website <span>↗</span></a></div>';if(p.id==='hotel')extras=`<a class="button button-blue" href="${p.url}" target="_blank" rel="noopener">Explore the Tableau story ↗</a>`;if(p.id==='grel')extras=`<div class="case-detail grel-study"><div class="case-actions"><a class="button button-blue" href="https://faazimalik1.github.io/faizan-motion-portfolio/projects/grel/prototype/index.html" target="_blank" rel="noopener">Open interactive prototype ↗</a><a class="button case-download" href="https://faazimalik1.github.io/faizan-motion-portfolio/projects/grel/Grel_UI_UX_Case_Study.pdf" target="_blank" rel="noopener">Download 16-page case study ↓</a></div>
<section><p class="eyebrow">01 / THE BRIEF</p><h3>Make the next step easier.</h3><p>Grel brings real estate learning, scripts and practical resources together. The redesign helps visitors understand the offer and compare learning plans with less uncertainty.</p></section>
<section><p class="eyebrow">02 / THE STARTING POINT</p><h3>Clarity before decoration.</h3><p>A review of the homepage and plan pages identified dense content, overlapping plan positioning and repeated questions. The redesign prioritises a concise value proposition, clearer plan differences and a consistent route from discovery to comparison.</p></section>
<section><p class="eyebrow">03 / REQUIREMENTS & STRUCTURE</p><h3>One clear route through the product.</h3><p>Communicate the learning offer quickly, make plan inclusions easy to scan, preserve an obvious route to comparison and adapt content to narrow screens.</p><div class="journey-steps">Home <span>→</span> Explore learning <span>→</span> Compare plans <span>→</span> Review a plan</div></section>
<section><p class="eyebrow">04 / WIREFRAMES</p><h3>Hierarchy first.</h3><p>Early layouts establish the message, learning categories, plan comparison and supporting questions before visual styling.</p><div class="grel-boards pair"><figure><a href="${asset('assets/grel-05-wireframe-home.png')}" target="_blank" rel="noopener"><img loading="lazy" src="${asset('assets/grel-05-wireframe-home.png')}" alt="Homepage wireframe"></a><figcaption>Homepage wireframe · Open to enlarge</figcaption></figure> <figure><a href="${asset('assets/grel-06-wireframe-plans.png')}" target="_blank" rel="noopener"><img loading="lazy" src="${asset('assets/grel-06-wireframe-plans.png')}" alt="Plans wireframe"></a><figcaption>Plans wireframe · Open to enlarge</figcaption></figure></div></section>
<section><p class="eyebrow">05 / VISUAL SYSTEM</p><h3>Calm, confident and consistent.</h3><p>Blue, navy and white separate primary actions from supporting content. Clear typography, shared buttons, cards and spacing make both pages feel like one product.</p><figure><a href="${asset('assets/grel-07-design-system.png')}" target="_blank" rel="noopener"><img loading="lazy" src="${asset('assets/grel-07-design-system.png')}" alt="Visual design system"></a><figcaption>Visual design system · Open to enlarge</figcaption></figure></section>
<section><p class="eyebrow">06 / FINAL INTERFACE</p><h3>Two pages. One coherent experience.</h3><p>The homepage introduces the learning offer in a progressive sequence. The plans page organises choices around comparison, with supporting details close to the decision.</p><div class="grel-boards pair"><figure><a href="${asset('assets/grel-01-home-desktop.png')}" target="_blank" rel="noopener"><img loading="lazy" src="${asset('assets/grel-01-home-desktop.png')}" alt="Desktop homepage"></a><figcaption>Desktop homepage · Open to enlarge</figcaption></figure> <figure><a href="${asset('assets/grel-02-plans-desktop.png')}" target="_blank" rel="noopener"><img loading="lazy" src="${asset('assets/grel-02-plans-desktop.png')}" alt="Desktop plan comparison"></a><figcaption>Desktop plan comparison · Open to enlarge</figcaption></figure></div></section>
<section><p class="eyebrow">07 / RESPONSIVE DESIGN</p><h3>Designed for smaller screens, too.</h3><p>Mobile layouts stack content and plan information into a clear reading order. The interactive prototype includes separate desktop and mobile views.</p><div class="grel-boards pair mobile-boards"><figure><a href="${asset('assets/grel-03-home-mobile.png')}" target="_blank" rel="noopener"><img loading="lazy" src="${asset('assets/grel-03-home-mobile.png')}" alt="Mobile homepage"></a><figcaption>Mobile homepage · Open to enlarge</figcaption></figure> <figure><a href="${asset('assets/grel-04-plans-mobile.png')}" target="_blank" rel="noopener"><img loading="lazy" src="${asset('assets/grel-04-plans-mobile.png')}" alt="Mobile plans"></a><figcaption>Mobile plans · Open to enlarge</figcaption></figure></div></section>
<section><p class="eyebrow">08 / VALIDATION & NEXT STEPS</p><h3>Keep improving the experience.</h3><p>The next step is to test whether prospective learners can explain the offer, identify a suitable plan and locate answers without assistance. Validate plan content with stakeholders and check keyboard navigation, focus order and screen reader behaviour during implementation.</p></section>
<div class="case-actions"><a class="button button-blue" href="https://faazimalik1.github.io/faizan-motion-portfolio/projects/grel/prototype/index.html" target="_blank" rel="noopener">Open interactive prototype ↗</a><a class="button case-download" href="https://faazimalik1.github.io/faizan-motion-portfolio/projects/grel/Grel_UI_UX_Case_Study.pdf" target="_blank" rel="noopener">Download 16-page case study ↓</a></div></div>`;$('#project-dialog-body').innerHTML=`<p class="eyebrow">${esc(p.label.toUpperCase())}</p><h2>${esc(p.title)}</h2><p class="project-description">${esc(p.description)}</p>${media}${extras}`;$('#project-position').textContent=`${currentProject+1} / ${projectSet.length}`;$('#project-dialog').scrollTop=0;}
function stepProject(d){currentProject=(currentProject+d+projectSet.length)%projectSet.length;showProject();}$('#project-prev').addEventListener('click',()=>stepProject(-1));$('#project-next').addEventListener('click',()=>stepProject(1));$('#project-dialog').addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();stepProject(1);}if(e.key==='ArrowLeft'){e.preventDefault();stepProject(-1);}});$('#project-dialog').addEventListener('close',()=>$('#project-dialog-body').replaceChildren());
$$('dialog').forEach(d=>{$('.dialog-close',d).addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});});
const film=$('#film-dialog'),filmVideo=$('video',film),preview=$('.motion-preview video'),toggle=$('.video-toggle'),signature=$('.brand-signature video');
$$('[data-play-reel]').forEach(b=>b.addEventListener('click',()=>{preview.pause();film.showModal();filmVideo.currentTime=0;filmVideo.play().catch(()=>{});}));film.addEventListener('close',()=>filmVideo.pause());toggle.addEventListener('click',()=>{if(preview.paused)preview.play().catch(()=>{});else preview.pause();});preview.addEventListener('play',()=>{toggle.textContent='Ⅱ';toggle.setAttribute('aria-label','Pause showreel preview');});preview.addEventListener('pause',()=>{toggle.textContent='▷';toggle.setAttribute('aria-label','Play showreel preview');});
const mediaObserver=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)e.target.pause();else if(!paused)e.target.play().catch(()=>{});}),{threshold:.5});mediaObserver.observe(preview);mediaObserver.observe(signature);
let enquiry='';$('#contact-form').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;if(!f.reportValidity())return;const d=new FormData(f);enquiry=`FAANOMATE PROJECT ENQUIRY\n\nName: ${d.get('name').trim()}\nEmail: ${d.get('email').trim()}\nService: ${d.get('service')}\n\nProject details\n${d.get('message').trim()}\n\nPrepared locally. This enquiry has not been sent.`;$('#enquiry-summary').textContent=enquiry;$('#form-status').textContent='Your enquiry is ready to download. No message has been sent.';$('#enquiry-dialog').showModal();});$('#download-enquiry').addEventListener('click',()=>{const u=URL.createObjectURL(new Blob([enquiry],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='FAANOMATE-project-enquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});$('#year').textContent=new Date().getFullYear();
const hero=$('.hero'),heroArt=$('.hero-art'),fine=matchMedia('(hover: hover) and (pointer: fine)'),motionButton=$('#motion-control');
function setMotion(v){paused=v;window.SITE_MOTION_PAUSED=v;document.documentElement.classList.toggle('motion-paused',v);motionButton.setAttribute('aria-pressed',String(v));motionButton.textContent=v?'Resume motion ▷':'Pause motion Ⅱ';if(v){preview.pause();signature.pause();heroArt.style.transform='none';}else heroArt.style.transform='';scrollUpdate();}
hero.addEventListener('pointermove',e=>{if(paused||!fine.matches)return;const r=hero.getBoundingClientRect();heroArt.style.setProperty('--px',((e.clientX-r.left)/r.width-.5)*2);heroArt.style.setProperty('--py',((e.clientY-r.top)/r.height-.5)*2);});hero.addEventListener('pointerleave',()=>{heroArt.style.setProperty('--px',0);heroArt.style.setProperty('--py',0);});
$$('.magnetic').forEach(b=>{b.addEventListener('pointermove',e=>{if(paused||!fine.matches)return;const r=b.getBoundingClientRect();b.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.12}px)`;});b.addEventListener('pointerleave',()=>b.style.transform='');});
const build=$('#build'),stage=$('.build-stage'),steps=$$('.build-step');let scheduled=false;let selectedStep=0;function showStep(i){selectedStep=i;stage.dataset.phase=i;steps.forEach((s,n)=>{s.classList.toggle('active',n===i);s.setAttribute('aria-pressed',String(n===i));});$('#stage-caption').textContent=['01 / STRUCTURE','02 / EXPRESSION','03 / EXPERIENCE'][i];}steps.forEach((s,i)=>s.addEventListener('click',()=>showStep(i)));showStep(0);function scrollUpdate(){scheduled=false;if(!paused&&innerWidth>700)heroArt.style.setProperty('--hero-scroll',`${Math.min(scrollY*.1,75)}px`);}
addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(scrollUpdate);}},{passive:true});motionButton.addEventListener('click',()=>setMotion(!paused));reduce.addEventListener('change',e=>setMotion(e.matches));setMotion(paused);
let wordIndex=0;const words=['Create.','Build.','Automate.'];setInterval(()=>{if(paused||document.hidden)return;const w=$('#rotating-word');w.classList.add('leaving');setTimeout(()=>{if(paused){w.classList.remove('leaving');return;}wordIndex=(wordIndex+1)%3;w.textContent=words[wordIndex];$('.verb-counter').textContent=`0${wordIndex+1} / 03`;w.classList.remove('leaving');},260);},2300);
const canvas=$('#particles'),ctx=canvas.getContext('2d');let cw=0,ch=0,time=0,inView=true,last=0;const dots=Array.from({length:42},(_,i)=>({x:Math.sin(i*127.1)*550,y:Math.cos(i*311.7)*400,z:Math.sin(i*74.7)*400}));function resizeCanvas(){const r=hero.getBoundingClientRect();cw=r.width;ch=r.height;const d=Math.min(devicePixelRatio||1,1.25);canvas.width=Math.round(cw*d);canvas.height=Math.round(ch*d);ctx.setTransform(d,0,0,d,0,0);}resizeCanvas();addEventListener('resize',resizeCanvas);new IntersectionObserver(es=>{inView=es[0].isIntersecting;}).observe(hero);function draw(ts){requestAnimationFrame(draw);if(!inView||document.hidden||ts-last<40)return;last=ts;if(!paused)time+=.0008;ctx.clearRect(0,0,cw,ch);dots.forEach(p=>{const x=p.x*Math.cos(time)-p.z*Math.sin(time),z=p.x*Math.sin(time)+p.z*Math.cos(time),s=600/(950+z);ctx.fillStyle=`rgba(82,149,255,${s*.45})`;ctx.beginPath();ctx.arc(cw*.65+x*s,ch*.5+p.y*s,Math.max(.6,s),0,Math.PI*2);ctx.fill();});}requestAnimationFrame(draw);
